"""
installer/backend/mirrors.py
"""

import subprocess
import logging
import re

log = logging.getLogger(__name__)

LOCALE_TO_COUNTRY = {
    "US": ("United States",    "United States"),
    "GB": ("United Kingdom",   "United Kingdom"),
    "DE": ("Germany",          "Germany"),
    "FR": ("France",           "France"),
    "NL": ("Netherlands",      "Netherlands"),
    "SE": ("Sweden",           "Sweden"),
    "NO": ("Norway",           "Norway"),
    "DK": ("Denmark",          "Denmark"),
    "FI": ("Finland",          "Finland"),
    "CH": ("Switzerland",      "Switzerland"),
    "AT": ("Austria",          "Austria"),
    "BE": ("Belgium",          "Belgium"),
    "PL": ("Poland",           "Poland"),
    "CZ": ("Czechia",          "Czech Republic"),
    "SK": ("Slovakia",         "Slovakia"),
    "HU": ("Hungary",          "Hungary"),
    "RO": ("Romania",          "Romania"),
    "BG": ("Bulgaria",         "Bulgaria"),
    "IT": ("Italy",            "Italy"),
    "ES": ("Spain",            "Spain"),
    "PT": ("Portugal",         "Portugal"),
    "GR": ("Greece",           "Greece"),
    "TR": ("Turkey",           "Turkey"),
    "RU": ("Russia",           "Russia"),
    "UA": ("Ukraine",          "Ukraine"),
    "BY": ("Belarus",          "Belarus"),
    "CN": ("China",            "China"),
    "JP": ("Japan",            "Japan"),
    "KR": ("South Korea",      "South Korea"),
    "TW": ("Taiwan",           "Taiwan"),
    "HK": ("Hong Kong",        "Hong Kong"),
    "SG": ("Singapore",        "Singapore"),
    "IN": ("India",            "India"),
    "AU": ("Australia",        "Australia"),
    "NZ": ("New Zealand",      "New Zealand"),
    "ZA": ("South Africa",     "South Africa"),
    "BR": ("Brazil",           "Brazil"),
    "CA": ("Canada",           "Canada"),
    "MX": ("Mexico",           "Mexico"),
    "AR": ("Argentina",        "Argentina"),
    "CL": ("Chile",            "Chile"),
    "IL": ("Israel",           "Israel"),
    "SA": ("Saudi Arabia",     "Saudi Arabia"),
}

# United States first, then the rest alphabetically — 'Murica! 🇺🇸
_sorted_rest = sorted(
    (v for k, v in LOCALE_TO_COUNTRY.items() if k != "US"),
    key=lambda x: x[1]
)
ALL_COUNTRIES = [("United States", "United States")] + _sorted_rest

FALLBACK_MIRRORLIST = """\
################################################################################
################# Arch Linux mirrorlist — fallback (static) ###################
################################################################################
# Generated by arch-installer when reflector was unavailable.
# For best performance, run reflector manually after installation:
#   reflector --country 'United States' --latest 10 --sort rate \\
#             --save /etc/pacman.d/mirrorlist

## Worldwide
Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch

## United States
Server = https://mirror.arizona.edu/archlinux/$repo/os/$arch
Server = https://mirrors.mit.edu/archlinux/$repo/os/$arch

## Europe
Server = https://mirror.hetzner.com/archlinux/$repo/os/$arch
Server = https://mirrors.nxtgen.com/archlinux-mirror/$repo/os/$arch
"""


def locale_to_country_code(locale: str) -> str:
    match = re.match(r"[a-z]+_([A-Z]+)", locale)
    if match:
        return match.group(1)
    return "US"


def country_code_to_reflector_name(code: str) -> str:
    entry = LOCALE_TO_COUNTRY.get(code.upper())
    return entry[0] if entry else "United States"


def fetch_mirrors(countries, protocols=None, sort_by="rate",
                  number=10, age=24):
    if protocols is None:
        protocols = ["https"]

    cmd = ["reflector"]
    for country in countries:
        cmd += ["--country", country]
    for protocol in protocols:
        cmd += ["--protocol", protocol]
    cmd += ["--sort", sort_by, "--latest", str(number),
            "--age", str(age), "--save", "/dev/stdout"]

    log.info("Running: %s", " ".join(cmd))

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        if result.returncode == 0 and result.stdout.strip():
            return True, result.stdout
        err = result.stderr.strip() or "reflector returned no output"
        log.warning("reflector failed: %s", err)
        return False, f"reflector failed: {err}"
    except FileNotFoundError:
        msg = "reflector is not installed. Install it with: sudo pacman -S reflector"
        log.warning(msg)
        return False, msg
    except subprocess.TimeoutExpired:
        msg = "reflector timed out (>60s). Check your network connection."
        log.warning(msg)
        return False, msg


def count_mirrors(mirrorlist: str) -> int:
    return sum(
        1 for line in mirrorlist.splitlines()
        if line.strip().startswith("Server =")
    )
